server {
    listen  20080;
    listen  [::]:20080;
    server_name localhost;

    root /usr/share/nginx/html;

    access_log off;
    autoindex off;
    server_tokens off;

    types {
        text/plain lua;
        text/plain fx;
    }

    gzip on;
    gzip_vary on;
    gzip_min_length 256;
    gzip_comp_level 6;
    gzip_types text/plain text/html text/css application/javascript application/json application/xml text/xml;

    open_file_cache max=5000 inactive=20s;
    open_file_cache_valid 30s;
    open_file_cache_min_uses 2;
    open_file_cache_errors on;
}